name: test schedule

on:
  schedule:
    - cron: '07 17 * * *' 
  workflow_dispatch:

jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Test schedule
        run: echo "Test schedule workflow triggered successfully."
